### ISSUE TITLE
"undefined method `require_relative' for Vault:Module" [probably cent6/ruby187 issue]

### ISSUE THREAD

**Issue by neoice** [jsok/hiera-vault#2]
here's a fairly minimal test case to reproduce:

``` shell
# launch your container
docker run --rm --link vault:vault -it centos:6 /bin/bash

# inside your container...
yum install -y ruby rubygems
gem install hiera
gem install hiera-vault

# verify connection to vault
curl http://vault:8200/v1/secret

# drop config file
cat << EOF > /hiera.yaml
:backends:
    - vault

:vault:
    :addr: http://vault:8200
    :token: REDACTED
EOF

hiera -c /hiera.yaml foo
```

```
/usr/lib/ruby/gems/1.8/gems/vault-0.1.3/lib/vault.rb:2: undefined method `require_relative' for Vault:Module (NoMethodError)
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/hiera-vault-0.1.1/lib/hiera/backend/vault_backend.rb:8:in `initialize'
    from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:205:in `new'
    from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:205:in `lookup'
    from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:203:in `each'
    from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:203:in `lookup'
    from /usr/lib/ruby/site_ruby/1.8/hiera.rb:60:in `lookup'
    from /usr/bin/hiera:225
```

the test case assumes you have a Docker container running vault named "vault". I did something like this to create my "test vault container".

``` docker
# Dockerfile
FROM cgswong/vault
COPY vault.cfg /vault.cfg
```

``` shell
docker build -t neoice/vault Dockerfile
docker run --privileged --name vault --rm -p 8200:8200 neoice/vault server -config=/vault.cfg
```

I was also able to reproduce the same error message on a CentOS6.6 virtual machine (no Docker, good old fashioned Puppet and PXE).

**Comment by jsok** [comment]
Can you try with a more modern ruby? It appears [Ruby 1.8.6 doesn't have `require_relative`](http://stackoverflow.com/questions/2681031/why-doesnt-relative-require-work-on-ruby-1-8-6)

**Comment by neoice** [comment]
RHEL/CentOS ship with 187. I believe Puppet ships an "all-in-one" package now with a sandboxed modern Ruby.

**Comment by jsok** [comment]
Ruby 1.9.3 is reaching end of life already, so I'm not so keen to start fixing issues for 1.8.
If you can find a simple work around please submit a PR.

**Comment by jsok** [comment]
Closing this issue for now. Will re-open if you decide to submit a PR for it.
